### ISSUE TITLE
Bug: Kabanero not able to use customized collections from GHE

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-foundation#104]
I am testing Champ scenario where collections are cloned, updated, rebuilt and published as a release in GHE following instructions at https://github.com/kabanero-io/collections.

 I updated the kabanero CR instance with updated collections in Github Enterprise. Kabanero instance after this change is not ready and throwing error.

```
oc get kabanero

NAME       AGE       VERSION   READY
kabanero   31m       0.2.0     False

```
```
kabaneroInstance:
    errorMessage: 'yaml: line 79: mapping values are not allowed in this context'
    ready: 'False'
    version: 0.2.0
```

I am not sure if this is due to Appsody defect https://github.com/appsody/appsody/issues/229
