### ISSUE TITLE
mismatch between Che version and kabaneroChe version

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-foundation#143]
kabaneroChe 0.6.0 is based on a fixed Che version 7.3.1, but when I enabled Che in Kabanero CR, it has Che version 7.4.0. It’s advised that the operator version needs to match the Che version, as it could cause undefined behavior. 

Below the version I see after enabled che
```
spec:
    che:
      cheOperatorInstance: {}
      enable: true
      kabaneroChe: {}
 
  status:
    che:
      cheOperator:
        version: 7.4.0
      kabaneroChe:
        version: 0.6.0
      kabaneroCheInstance:
        cheImage: kabanero/kabanero-che
        cheImageTag: 0.6.0
        cheWorkspaceClusterRole: eclipse-codewind
      ready: "True"
```
