### ISSUE TITLE
Kabanero instance is not ready after installing kabanero 0.5 rc2

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-foundation#151]
When I looked at the kabanero instance after installing 0.5 rc2 driver, it is not showing ready. There were no errors during install.

` oc edit kabanero kabanero -n kabanero`
```
kabaneroInstance:
errorMessage: One or more resource dependencies are not ready.
    ready: "False"
    version: 0.5.0
  serverless:
    knativeServing:
      errorMessage: Knative serving not ready.
      ready: "False"
      version: 0.9.0
    ready: "False"
    version: 1.2.0
```
