### ISSUE TITLE
Support Github protocol on Kabanero CRs

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-foundation#159]
Any references to GitHub URLs be changed to use GitHub API. For example instead of

```      pipelines:
        - id: default
          url: https://github.com/kabanero-io/pipelines/releases/download/0.7.0/default.pipeline.tar.gz
          sha256: 0123456789abcdef 
```

The Stack would support something like:
```
      pipelines:
        - id: default
          github:
             url: https://github.com/kabanero-io/kabanero-pipelines
             revision: 0.5.0 (defaults to master) 
```

Or something similar if we want to support using the GitHub release API. The operator would lookup credentials for such endpoints using the same way as Tekton. This would provide GitHub Enterprise support and potentially add ability to point to the latest release of pipelines 0.2 just like the Stack image does.

This method could also be extended to support various other protocols later on. For example:

```     pipelines:
        - id: default
          http:
             url: https://github.com/kabanero-io/pipelines/releases/download/0.7.0/default.pipeline.tar.gz
             skipCertVerification: false
             sha256: 0123456789abcdef
```
