### ISSUE TITLE
Operator reactivates a collection after it was deactivated

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-foundation#85]
Operator reactivates java-microprofile collection after it was deactivated

java-microprofile is a default collection in the operator and it will be reactivated automatically if deactivated from the Kabanero CLI

In fact all dectivated collections get reactivated when java-microprofile is deactivated

If we turn off the operator with:

`kubectl scale deployment kabanero-operator --replicas=0`

The problem goes away

**Comment by davco01a** [comment]
this default collection may need to be removed from the operator

Or code may need to be added to the Kabanero CLI microservice to prevent deactivation of the `java-microprofile` collection

**Comment by kaczyns** [comment]
The operator can be configured to not automatically start the collections in the repository.
```yaml
spec:
  collections: 
    # A list of those repositories which are searched for collections
    repositories: 
    - name: incubator
      url: https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml
      # Activates a default set of collections
      activateDefaultCollections: false
```
However it sounds like you can deactivate other collections, and they are not re-activated... which sounds like a problem to me.  The `java-microprofile` collection should not control whether all of the other collections are re-activated.
